version: '3'

services:
    app_red:
        build: 
            context: httpd
        ports:
            - 8090:80
        volumes:
            - ./www:/var/www/html
            - ./httpd/redirector.project.conf:/etc/apache2/sites-available/000-default.conf
            - ./httpd/apache2.conf:/etc/apache2/apache2.conf
        container_name: app_red
        networks:
            - red-network
    db_red:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: mysql:8.0
        container_name: db_red
        ports:
            - "33062:3306"        
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
        volumes:
            - ./dbdata:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - red-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8082:80
        environment:
            - PMA_ARBITRARY=1
        container_name: phpmyadmin_red
        networks:
            - red-network
#Docker Networks
networks:
    red-network:
        driver: bridge
